version: '3.8'

services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    expose:
      - "3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=KaryaApp123
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=production
      - SECRET_KEY_BASE=7e0d468f2b0f07dc74ba4110cb674d55ef62649aadb22de9105f181e145b921fc82bdbd64a008fb607b5b9b41a92b40f1c521752d933270555f8036eae77352f
    depends_on:
      - db
      - redis

  resque:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=KaryaApp123
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=production
      - SECRET_KEY_BASE=7e0d468f2b0f07dc74ba4110cb674d55ef62649aadb22de9105f181e145b921fc82bdbd64a008fb607b5b9b41a92b40f1c521752d933270555f8036eae77352f

    depends_on:
      - db
      - redis
    command: bundle exec rake resque:work QUEUE='*'

  resque-scheduler:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=KaryaApp123
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=production
      - SECRET_KEY_BASE=7e0d468f2b0f07dc74ba4110cb674d55ef62649aadb22de9105f181e145b921fc82bdbd64a008fb607b5b9b41a92b40f1c521752d933270555f8036eae77352f

    depends_on:
      - db
      - redis
    command: bundle exec rake resque:scheduler

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=KaryaApp123
      - MYSQL_DATABASE=production_rails_app_production
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app

volumes:
  mysql_data:
  redis_data:
