version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=KaryaApp123
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=production
      - SECRET_KEY_BASE=7e0d468f2b0f07dc74ba4110cb674d55ef62649aadb22de9105f181e145b921fc82bdbd64a008fb607b5b9b41a92b40f1c521752d933270555f8036eae77352f
    depends_on:
      - db
      - redis
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails s -b 0.0.0.0"

  resque:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=KaryaApp123
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=production
      - SECRET_KEY_BASE=7e0d468f2b0f07dc74ba4110cb674d55ef62649aadb22de9105f181e145b921fc82bdbd64a008fb607b5b9b41a92b40f1c521752d933270555f8036eae77352f

    depends_on:
      - db
      - redis
    command: bundle exec rake resque:work QUEUE='*'

  resque-scheduler:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=KaryaApp123
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=production
      - SECRET_KEY_BASE=7e0d468f2b0f07dc74ba4110cb674d55ef62649aadb22de9105f181e145b921fc82bdbd64a008fb607b5b9b41a92b40f1c521752d933270555f8036eae77352f

    depends_on:
      - db
      - redis
    command: bundle exec rake resque:scheduler

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=KaryaApp123
      - MYSQL_DATABASE=production_rails_app_production
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  redis_data:
