default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: KaryaApp123
  host: <%= ENV.fetch("DATABASE_HOST") { "db"  } %>
  port: 3306

development:
  database: karya-app-dev
  <<: *default

test:
  <<: *default
  database: karya-app-test

production:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") { "karya-app-prod" } %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  port: <%= ENV.fetch("DATABASE_PORT") { "3306" } %>